# CI项目
name: WRT-TEST

# CI计划
on:
  # 手动触发
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string

# CI权限 - 最小权限原则
permissions:
  contents: write
  actions: write

# CI任务
jobs:
  config:
    name: IPQ60XX-AX18-LITE
    # 调用公用编译核心 WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    secrets: inherit
    with:
      # 编译配置
      WRT_CONFIG: IPQ60XX-AX18-LITE
      # 默认主题
      WRT_THEME: bootstrap
      # 默认主机名
      WRT_NAME: OpenWrt
      # 默认管理地址
      WRT_IP: 192.168.0.1
      # 登录密码
      WRT_PW: 无
      # 源码链接
      WRT_REPO: https://github.com/VIKINGYFY/immortalwrt.git
      # 源码分支
      WRT_BRANCH: main
      # 源码名称
      WRT_SOURCE: VIKINGYFY/immortalwrt
      # 插件调整
      WRT_PACKAGE: ${{ inputs.PACKAGE }}
      # 仅输出配置文件，不编译固件
      WRT_TEST: 'true'
